### ISSUE TITLE
Lack of documentation

### ISSUE THREAD

**Issue by davy7125** [musescore/sftools#12]
Hi,

Several information could be useful:
- a readme could be found, with the list of dependencies (ogg, vorbis, Qt, ...), the explanation of the variable "smallSf"
- the differences between Sf2 (a kind of specification)
  - raw data replaced by ogg,
  - flag 0x10 added to sfSampleType,
  - loop start and end are stored based on the beginning of the corresponding sample and not on the beginning of the smpl chunk anymore,
  - 24-bit mode disabled.

**Comment by lasconic** [comment]
A README has been added listing the dependencies. 
More work to be done. I don't have the knowledge to write the specification.

**Comment by mirabilos** [comment]
I’ve written a manpage: https://github.com/mirabilos/sftools/blob/debian/debian/musescore-sfconvert.1

@lasconic do you wish to have this added via a PR? I’m unsure about how to get it added to cmake, and I had to rename the binary from `sfconvert` to `musescore-sfconvert` in Debian because `sfconvert` already exists in the `audiofile-tools` package, so I’d either need to change the manpage to `sfconvert` before submitting, or you’d need to rename this in here, too.

In general, have a look at https://github.com/mirabilos/sftools/tree/debian/debian/patches if you find something worthwhile. And talk to me ;)

**Comment by lasconic** [comment]
I would rather call "convertsf" or "convert-soundfont" and keep MuseScore out of it. Feel free to change the name of the binary. Sure PR are welcome.

**Comment by lasconic** [comment]
manpage merged.
